<?php
define("VALID","正确！");
define("_ERR_ADMIN_LOGIN","用户名或密码不正确！");
define("ERROR_NULL","不能为空！");
define("ERROR_SELECT","必须选择！");
define("ERROR_INVALID","格式不正确！");
define("ERROR_TOO_SHORT","长度太短！");
define("ERROR_TOO_LONG","长度过长！");
define("ERROR_HAVE_EXIST","%已存在！");
define("ERROR_PASSWORD_DIFFERENCE","两次密码不一样！");
define("ERROR_FILE_NULL","请上传文件！");
define("ERROR_FILE_FAIL","文件上传失败！");
define("ERROR_IMAGE_NULL","请上传图片！");
define("ERROR_IMAGE_INVALID","格式不正确！");
define("ERROR_IMAGE_UPLOAD","图片上传出错！");

define("ERR_NO_PERMIT","对不起，您没有此权限！");
define("ERR_NO_DATA","暂无数据.....");
define("ERR_PASSWORD_NEW","新密码格式不正确！");







?>